name: Sync to Personal Repo

on:
  push:
    branches:
      - main  # Anpassen falls Branch anders hei√üt

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Org Repo
        uses: actions/checkout@v3

      - name: Push to Personal Repo
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "sync@bot.local"
          git remote add personal https://x-access-token:${PERSONAL_REPO_TOKEN}@github.com/Redminer9630de/Redminer9630.git
          git push personal HEAD:main --force
